// Seed file for exercise database
// Contains 100+ exercises covering all movement patterns, equipment types, and difficulty levels

const exercises = [
  // SQUAT PATTERN
  { name: 'Barbell Back Squat', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes', 'core'], movement_pattern: 'squat', equipment_required: 'barbell', difficulty_level: 'intermediate', form_cues: 'Keep chest up, knees track over toes, descend until thighs parallel to floor', common_mistakes: 'Knee valgus, forward lean, insufficient depth' },
  { name: 'Barbell Front Squat', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes', 'core', 'shoulders'], movement_pattern: 'squat', equipment_required: 'barbell', difficulty_level: 'advanced', form_cues: 'Elbows up, keep torso upright, core tight', common_mistakes: 'Dropping elbows, forward lean' },
  { name: 'Goblet Squat', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes', 'core'], movement_pattern: 'squat', equipment_required: 'dumbbells', difficulty_level: 'beginner', form_cues: 'Hold weight at chest, sit back and down', common_mistakes: 'Leaning forward, not going deep enough' },
  { name: 'Dumbbell Squat', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes', 'core'], movement_pattern: 'squat', equipment_required: 'dumbbells', difficulty_level: 'beginner', form_cues: 'Hold dumbbells at sides, squat down', common_mistakes: 'Forward lean, knee collapse' },
  { name: 'Bodyweight Squat', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes'], movement_pattern: 'squat', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Feet shoulder-width, sit back and down', common_mistakes: 'Knees caving in, insufficient depth' },
  { name: 'Bulgarian Split Squat', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes'], movement_pattern: 'squat', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Rear foot elevated, front leg does the work', common_mistakes: 'Leaning too far forward, knee going past toes' },
  { name: 'Walking Lunges', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes'], movement_pattern: 'squat', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Step forward, lower back knee, push through front heel', common_mistakes: 'Stride too short, forward lean' },
  { name: 'Reverse Lunges', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes'], movement_pattern: 'squat', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Step back, lower down, push through front foot', common_mistakes: 'Leaning forward, not enough depth' },
  { name: 'Leg Press', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes'], movement_pattern: 'squat', equipment_required: 'machines', difficulty_level: 'beginner', form_cues: 'Full range of motion, control the weight', common_mistakes: 'Partial reps, locking knees' },
  { name: 'Pistol Squat', primary_muscle_group: 'legs', secondary_muscle_groups: ['core'], movement_pattern: 'squat', equipment_required: 'bodyweight', difficulty_level: 'advanced', form_cues: 'One leg extended, balance and squat down', common_mistakes: 'Losing balance, insufficient depth' },

  // HINGE PATTERN
  { name: 'Barbell Deadlift', primary_muscle_group: 'back', secondary_muscle_groups: ['legs', 'glutes', 'core'], movement_pattern: 'hinge', equipment_required: 'barbell', difficulty_level: 'intermediate', form_cues: 'Hinge at hips, keep back straight, drive through heels', common_mistakes: 'Rounded back, bar drifting away' },
  { name: 'Romanian Deadlift', primary_muscle_group: 'back', secondary_muscle_groups: ['legs', 'glutes'], movement_pattern: 'hinge', equipment_required: 'barbell', difficulty_level: 'intermediate', form_cues: 'Hinge at hips, slight knee bend, feel hamstring stretch', common_mistakes: 'Bending knees too much, rounding back' },
  { name: 'Dumbbell Romanian Deadlift', primary_muscle_group: 'back', secondary_muscle_groups: ['legs', 'glutes'], movement_pattern: 'hinge', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Hinge at hips, dumbbells close to legs', common_mistakes: 'Rounding back, too much knee bend' },
  { name: 'Good Mornings', primary_muscle_group: 'back', secondary_muscle_groups: ['glutes', 'hamstrings'], movement_pattern: 'hinge', equipment_required: 'barbell', difficulty_level: 'advanced', form_cues: 'Hinge at hips, keep back straight', common_mistakes: 'Rounding back, going too deep' },
  { name: 'Hip Thrust', primary_muscle_group: 'glutes', secondary_muscle_groups: ['legs'], movement_pattern: 'hinge', equipment_required: 'barbell', difficulty_level: 'intermediate', form_cues: 'Upper back on bench, drive hips up, squeeze glutes', common_mistakes: 'Hyperextending, not full range' },
  { name: 'Glute Bridge', primary_muscle_group: 'glutes', secondary_muscle_groups: ['legs'], movement_pattern: 'hinge', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Lift hips up, squeeze glutes at top', common_mistakes: 'Not going high enough, arching back' },
  { name: 'Single Leg Romanian Deadlift', primary_muscle_group: 'back', secondary_muscle_groups: ['glutes', 'core'], movement_pattern: 'hinge', equipment_required: 'dumbbells', difficulty_level: 'advanced', form_cues: 'Balance on one leg, hinge at hip, keep back straight', common_mistakes: 'Losing balance, rounding back' },
  { name: 'Kettlebell Swing', primary_muscle_group: 'glutes', secondary_muscle_groups: ['legs', 'core'], movement_pattern: 'hinge', equipment_required: 'kettlebells', difficulty_level: 'intermediate', form_cues: 'Hinge at hips, explosive hip drive, swing to chest height', common_mistakes: 'Squatting instead of hinging, using arms' },

  // PUSH HORIZONTAL
  { name: 'Barbell Bench Press', primary_muscle_group: 'chest', secondary_muscle_groups: ['shoulders', 'triceps'], movement_pattern: 'push_horizontal', equipment_required: 'barbell', difficulty_level: 'intermediate', form_cues: 'Retract scapula, control descent, press up', common_mistakes: 'Bouncing bar, flaring elbows' },
  { name: 'Dumbbell Bench Press', primary_muscle_group: 'chest', secondary_muscle_groups: ['shoulders', 'triceps'], movement_pattern: 'push_horizontal', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Control the weight, full range of motion', common_mistakes: 'Dropping too fast, not going deep enough' },
  { name: 'Incline Dumbbell Press', primary_muscle_group: 'chest', secondary_muscle_groups: ['shoulders', 'triceps'], movement_pattern: 'push_horizontal', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Bench at 30-45 degrees, press up and slightly forward', common_mistakes: 'Too steep angle, flaring elbows' },
  { name: 'Push-ups', primary_muscle_group: 'chest', secondary_muscle_groups: ['shoulders', 'triceps', 'core'], movement_pattern: 'push_horizontal', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Body in straight line, lower until chest nearly touches floor', common_mistakes: 'Sagging hips, partial range' },
  { name: 'Incline Push-ups', primary_muscle_group: 'chest', secondary_muscle_groups: ['shoulders', 'triceps'], movement_pattern: 'push_horizontal', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Feet on floor, hands elevated, easier variation', common_mistakes: 'Not going deep enough' },
  { name: 'Decline Push-ups', primary_muscle_group: 'chest', secondary_muscle_groups: ['shoulders', 'triceps'], movement_pattern: 'push_horizontal', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Feet elevated, harder variation', common_mistakes: 'Sagging hips' },
  { name: 'Cable Chest Fly', primary_muscle_group: 'chest', secondary_muscle_groups: ['shoulders'], movement_pattern: 'push_horizontal', equipment_required: 'cables', difficulty_level: 'intermediate', form_cues: 'Slight elbow bend, arc motion, squeeze at center', common_mistakes: 'Straight arms, too much weight' },
  { name: 'Dumbbell Fly', primary_muscle_group: 'chest', secondary_muscle_groups: ['shoulders'], movement_pattern: 'push_horizontal', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Wide arc, slight elbow bend, control the stretch', common_mistakes: 'Too much weight, straight arms' },
  { name: 'Machine Chest Press', primary_muscle_group: 'chest', secondary_muscle_groups: ['shoulders', 'triceps'], movement_pattern: 'push_horizontal', equipment_required: 'machines', difficulty_level: 'beginner', form_cues: 'Full range of motion, control the weight', common_mistakes: 'Partial reps' },

  // PUSH VERTICAL
  { name: 'Barbell Overhead Press', primary_muscle_group: 'shoulders', secondary_muscle_groups: ['triceps', 'core'], movement_pattern: 'push_vertical', equipment_required: 'barbell', difficulty_level: 'intermediate', form_cues: 'Press straight up, brace core, slight lean back', common_mistakes: 'Arching back too much, forward lean' },
  { name: 'Dumbbell Shoulder Press', primary_muscle_group: 'shoulders', secondary_muscle_groups: ['triceps'], movement_pattern: 'push_vertical', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Press up, slight forward angle', common_mistakes: 'Flaring elbows, arching back' },
  { name: 'Seated Dumbbell Press', primary_muscle_group: 'shoulders', secondary_muscle_groups: ['triceps'], movement_pattern: 'push_vertical', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Back support, press straight up', common_mistakes: 'Using momentum' },
  { name: 'Pike Push-ups', primary_muscle_group: 'shoulders', secondary_muscle_groups: ['triceps'], movement_pattern: 'push_vertical', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Hips high, body in inverted V, lower head to floor', common_mistakes: 'Not enough depth' },
  { name: 'Handstand Push-ups', primary_muscle_group: 'shoulders', secondary_muscle_groups: ['triceps', 'core'], movement_pattern: 'push_vertical', equipment_required: 'bodyweight', difficulty_level: 'advanced', form_cues: 'Against wall, lower head to floor, press up', common_mistakes: 'Losing balance, partial range' },
  { name: 'Lateral Raises', primary_muscle_group: 'shoulders', secondary_muscle_groups: [], movement_pattern: 'push_vertical', equipment_required: 'dumbbells', difficulty_level: 'beginner', form_cues: 'Slight bend in elbow, raise to shoulder height', common_mistakes: 'Using momentum, too much weight' },
  { name: 'Front Raises', primary_muscle_group: 'shoulders', secondary_muscle_groups: [], movement_pattern: 'push_vertical', equipment_required: 'dumbbells', difficulty_level: 'beginner', form_cues: 'Raise to shoulder height, control descent', common_mistakes: 'Using momentum' },
  { name: 'Cable Lateral Raises', primary_muscle_group: 'shoulders', secondary_muscle_groups: [], movement_pattern: 'push_vertical', equipment_required: 'cables', difficulty_level: 'beginner', form_cues: 'Constant tension, raise to side', common_mistakes: 'Too much weight' },

  // PULL HORIZONTAL
  { name: 'Barbell Bent-Over Row', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_horizontal', equipment_required: 'barbell', difficulty_level: 'intermediate', form_cues: 'Hinge at hips, pull to lower chest, squeeze back', common_mistakes: 'Rounded back, using momentum' },
  { name: 'Dumbbell Row', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_horizontal', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Support with other arm, pull to hip, squeeze', common_mistakes: 'Twisting, using momentum' },
  { name: 'Seated Cable Row', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_horizontal', equipment_required: 'cables', difficulty_level: 'beginner', form_cues: 'Pull to lower chest, squeeze shoulder blades', common_mistakes: 'Leaning back, using momentum' },
  { name: 'T-Bar Row', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_horizontal', equipment_required: 'barbell', difficulty_level: 'intermediate', form_cues: 'Bent over, pull to chest', common_mistakes: 'Rounded back' },
  { name: 'Chest Supported Row', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_horizontal', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Supported on bench, pull to sides', common_mistakes: 'Not squeezing back' },
  { name: 'Inverted Row', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_horizontal', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Body straight, pull chest to bar', common_mistakes: 'Sagging hips' },
  { name: 'Face Pulls', primary_muscle_group: 'shoulders', secondary_muscle_groups: ['back'], movement_pattern: 'pull_horizontal', equipment_required: 'cables', difficulty_level: 'beginner', form_cues: 'Pull to face level, external rotation', common_mistakes: 'Too much weight, wrong angle' },

  // PULL VERTICAL
  { name: 'Pull-ups', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_vertical', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Hang full, pull until chin over bar, control descent', common_mistakes: 'Kipping, partial range' },
  { name: 'Chin-ups', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_vertical', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Underhand grip, pull up', common_mistakes: 'Kipping' },
  { name: 'Assisted Pull-ups', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_vertical', equipment_required: 'machines', difficulty_level: 'beginner', form_cues: 'Use assistance, full range of motion', common_mistakes: 'Too much assistance' },
  { name: 'Lat Pulldown', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_vertical', equipment_required: 'cables', difficulty_level: 'beginner', form_cues: 'Pull to upper chest, squeeze lats', common_mistakes: 'Pulling behind neck, using momentum' },
  { name: 'Cable Pull-down', primary_muscle_group: 'back', secondary_muscle_groups: ['biceps'], movement_pattern: 'pull_vertical', equipment_required: 'cables', difficulty_level: 'beginner', form_cues: 'Pull to chest, lean back slightly', common_mistakes: 'Too much lean' },

  // ARMS - BICEPS
  { name: 'Barbell Bicep Curl', primary_muscle_group: 'arms', secondary_muscle_groups: [], movement_pattern: 'pull_horizontal', equipment_required: 'barbell', difficulty_level: 'beginner', form_cues: 'Keep elbows still, curl up, control down', common_mistakes: 'Swinging, using momentum' },
  { name: 'Dumbbell Bicep Curl', primary_muscle_group: 'arms', secondary_muscle_groups: [], movement_pattern: 'pull_horizontal', equipment_required: 'dumbbells', difficulty_level: 'beginner', form_cues: 'Alternate or together, full range', common_mistakes: 'Swinging' },
  { name: 'Hammer Curl', primary_muscle_group: 'arms', secondary_muscle_groups: [], movement_pattern: 'pull_horizontal', equipment_required: 'dumbbells', difficulty_level: 'beginner', form_cues: 'Neutral grip, curl up', common_mistakes: 'Swinging' },
  { name: 'Cable Bicep Curl', primary_muscle_group: 'arms', secondary_muscle_groups: [], movement_pattern: 'pull_horizontal', equipment_required: 'cables', difficulty_level: 'beginner', form_cues: 'Constant tension, control the weight', common_mistakes: 'Too much weight' },
  { name: 'Concentration Curl', primary_muscle_group: 'arms', secondary_muscle_groups: [], movement_pattern: 'pull_horizontal', equipment_required: 'dumbbells', difficulty_level: 'beginner', form_cues: 'Seated, arm supported, isolate bicep', common_mistakes: 'Using other muscles' },

  // ARMS - TRICEPS
  { name: 'Close-Grip Bench Press', primary_muscle_group: 'arms', secondary_muscle_groups: ['chest'], movement_pattern: 'push_horizontal', equipment_required: 'barbell', difficulty_level: 'intermediate', form_cues: 'Hands shoulder-width, press up', common_mistakes: 'Flaring elbows' },
  { name: 'Tricep Dips', primary_muscle_group: 'arms', secondary_muscle_groups: ['shoulders'], movement_pattern: 'push_vertical', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Lower until elbows at 90 degrees, press up', common_mistakes: 'Not going deep enough, shoulder pain' },
  { name: 'Overhead Tricep Extension', primary_muscle_group: 'arms', secondary_muscle_groups: [], movement_pattern: 'push_vertical', equipment_required: 'dumbbells', difficulty_level: 'beginner', form_cues: 'Overhead, lower behind head, extend', common_mistakes: 'Flaring elbows' },
  { name: 'Tricep Pushdown', primary_muscle_group: 'arms', secondary_muscle_groups: [], movement_pattern: 'push_vertical', equipment_required: 'cables', difficulty_level: 'beginner', form_cues: 'Elbows at sides, extend down', common_mistakes: 'Moving elbows' },
  { name: 'Diamond Push-ups', primary_muscle_group: 'arms', secondary_muscle_groups: ['chest'], movement_pattern: 'push_horizontal', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Hands in diamond shape, focus on triceps', common_mistakes: 'Sagging hips' },
  { name: 'Skull Crushers', primary_muscle_group: 'arms', secondary_muscle_groups: [], movement_pattern: 'push_vertical', equipment_required: 'barbell', difficulty_level: 'intermediate', form_cues: 'Lower to forehead, extend up', common_mistakes: 'Flaring elbows' },

  // LEGS - QUADRICEPS
  { name: 'Leg Extension', primary_muscle_group: 'legs', secondary_muscle_groups: [], movement_pattern: 'squat', equipment_required: 'machines', difficulty_level: 'beginner', form_cues: 'Full range, control the weight', common_mistakes: 'Too fast, partial range' },
  { name: 'Leg Curl', primary_muscle_group: 'legs', secondary_muscle_groups: [], movement_pattern: 'hinge', equipment_required: 'machines', difficulty_level: 'beginner', form_cues: 'Curl heels to glutes', common_mistakes: 'Using momentum' },
  { name: 'Calf Raises', primary_muscle_group: 'legs', secondary_muscle_groups: [], movement_pattern: 'squat', equipment_required: 'dumbbells', difficulty_level: 'beginner', form_cues: 'Rise up on toes, full range', common_mistakes: 'Partial range' },
  { name: 'Seated Calf Raises', primary_muscle_group: 'legs', secondary_muscle_groups: [], movement_pattern: 'squat', equipment_required: 'machines', difficulty_level: 'beginner', form_cues: 'Seated, raise on toes', common_mistakes: 'Partial range' },

  // CORE
  { name: 'Plank', primary_muscle_group: 'core', secondary_muscle_groups: [], movement_pattern: 'carry', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Body straight line, engage core', common_mistakes: 'Sagging hips, raised butt' },
  { name: 'Side Plank', primary_muscle_group: 'core', secondary_muscle_groups: [], movement_pattern: 'carry', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Body straight, hold position', common_mistakes: 'Sagging hips' },
  { name: 'Dead Bug', primary_muscle_group: 'core', secondary_muscle_groups: [], movement_pattern: 'carry', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Lower opposite arm and leg, keep back flat', common_mistakes: 'Arching back' },
  { name: 'Russian Twists', primary_muscle_group: 'core', secondary_muscle_groups: [], movement_pattern: 'rotation', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Rotate torso, keep core engaged', common_mistakes: 'Using momentum' },
  { name: 'Crunches', primary_muscle_group: 'core', secondary_muscle_groups: [], movement_pattern: 'rotation', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Lift shoulders, don\'t pull neck', common_mistakes: 'Pulling on neck' },
  { name: 'Bicycle Crunches', primary_muscle_group: 'core', secondary_muscle_groups: [], movement_pattern: 'rotation', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Alternate bringing knee to opposite elbow', common_mistakes: 'Using momentum' },
  { name: 'Hanging Leg Raises', primary_muscle_group: 'core', secondary_muscle_groups: ['legs'], movement_pattern: 'carry', equipment_required: 'bodyweight', difficulty_level: 'advanced', form_cues: 'Hang from bar, raise legs, control descent', common_mistakes: 'Swinging, using momentum' },
  { name: 'Ab Wheel Rollout', primary_muscle_group: 'core', secondary_muscle_groups: [], movement_pattern: 'carry', equipment_required: 'bodyweight', difficulty_level: 'advanced', form_cues: 'Roll out slowly, keep core tight', common_mistakes: 'Going too far, losing form' },
  { name: 'Mountain Climbers', primary_muscle_group: 'core', secondary_muscle_groups: ['legs'], movement_pattern: 'carry', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Alternate bringing knees to chest', common_mistakes: 'Sagging hips' },

  // CARRY PATTERN
  { name: 'Farmer\'s Walk', primary_muscle_group: 'core', secondary_muscle_groups: ['legs', 'back'], movement_pattern: 'carry', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Walk with heavy weights, keep posture', common_mistakes: 'Rounded back' },
  { name: 'Suitcase Carry', primary_muscle_group: 'core', secondary_muscle_groups: ['legs'], movement_pattern: 'carry', equipment_required: 'dumbbells', difficulty_level: 'intermediate', form_cues: 'Carry on one side, resist lateral flexion', common_mistakes: 'Leaning to side' },

  // CARDIO/CONDITIONING
  { name: 'Burpees', primary_muscle_group: 'legs', secondary_muscle_groups: ['chest', 'core'], movement_pattern: 'squat', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Squat, jump back to plank, push-up, jump forward, jump up', common_mistakes: 'Incomplete movements' },
  { name: 'Jump Squats', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes'], movement_pattern: 'squat', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Squat down, explode up, land softly', common_mistakes: 'Landing hard, poor form' },
  { name: 'Box Jumps', primary_muscle_group: 'legs', secondary_muscle_groups: ['glutes'], movement_pattern: 'squat', equipment_required: 'bodyweight', difficulty_level: 'intermediate', form_cues: 'Jump onto box, step down', common_mistakes: 'Landing on box incorrectly' },
  { name: 'High Knees', primary_muscle_group: 'legs', secondary_muscle_groups: ['core'], movement_pattern: 'squat', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Run in place, bring knees high', common_mistakes: 'Not going high enough' },
  { name: 'Jumping Jacks', primary_muscle_group: 'legs', secondary_muscle_groups: ['shoulders'], movement_pattern: 'squat', equipment_required: 'bodyweight', difficulty_level: 'beginner', form_cues: 'Jump feet out, arms up, return', common_mistakes: 'Poor coordination' },
]

module.exports = { exercises }

